name: .NET Core Release

on:
  push:
    #branches: [ "master" ]
    tags:
      #- "[0-9]+.[0-9]+.[0-9]+"
      - "v*"
  pull_request:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
    tags:
      - "v*"

jobs:

  build:
    strategy:
      matrix:
        arch: [x86, x64, ARM64, Fw-x86, Fw-x64, Fw-ARM, Fw-ARM64, Any CPU]
        #arch: [x86]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: WpfMykImageViewer.sln                      # Replace with your solution name, i.e. MyWpfApp.sln.

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Build
    - name: Build
      run: dotnet publish .\WpfMykImageViewer\WpfMykImageViewer.csproj -c Release -p:Platform="${{matrix.arch}}" -o output

    #debug
    - name: Debug
      run: |
        ls
        ls ./output

    # Upload Artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        #name: artifacts_win-${{matrix.arch}}
        name: WpfMykImageViewer-win-${{matrix.arch}}
        #path: build_win_${{matrix.arch}}/install
        path: ./output

  Release:
    needs: build #build が成功したら
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check cd & move cd
        run: |
          ls

     # Artifactsのダウンロード
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifact

    # Create Archive
      - name: Create Archive
        run: | 
          ls .\artifact
          .\archive.ps1 ".\artifact" ".\artifact"

    # Create Release
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          omitBody: true
          artifacts: './artifact/*'
          token: ${{ secrets.GITHUB_TOKEN }}
